### ISSUE TITLE
All propTypes result to any, if PropTypes instead of React.PropTypes is used

### ISSUE THREAD

**Issue by timbru31** [KnisterPeter/react-to-typescript-definitions#146] opened 2016-07-26 10:06 UTC
Currently all propTypes default to `any`, if the following syntax is used instead of `React.PropTypes`:

```jsx
import React, {PropTypes} from 'react';
...

	static propTypes = {
		className: PropTypes.string,
		component: PropTypes.string,
		renderOptions: PropTypes.object,
		children: PropTypes.element,
		order: PropTypes.string,
		source: PropTypes.string
	};
```

The culprit is in https://github.com/KnisterPeter/react-to-typescript-definitions/blob/master/index.ts#L155-L157

In the mentioned example above the `node.type` is still a `MemberExpression`, but the `node.object.type` is `Identifier` and the `node.object.name` is `PropTypes`

using v0.11.1

**Comment by KnisterPeter** [comment] 2016-07-27 06:22
Duplicate of #119

**Closed by KnisterPeter** 2016-07-27 06:22 UTC
Labels: bug
